### ISSUE TITLE
Add a Git Tag for OpenUPM

### ISSUE THREAD

**Issue by brogan89** [nementic-games/grouping-tool#1]
Hi, I'm unable to install using OpenUPM because there is no git tag.
https://openupm.com/packages/com.nementic.grouping-tool/

**Comment by chrisyarbrough** [comment]
Does this work:
https://github.com/nementic-games/grouping-tool/releases/tag/v1.1.2

If so, we'll be tagging our releases in the future. Thank you for bringing this up!

**Comment by brogan89** [comment]
Not yet. I'm guessing it takes a while for the registry to update? I'm not actually sure how all that works. 
I'll check at a later time. I'm using the package fine from source atm, I just like using OpenUPM is all. 
Thanks for the quick action and response! 😃

**Comment by brogan89** [comment]
Looks like it works now! Thanks for that.
